"""initial schema

Revision ID: f33fde83ba9c
Revises: 
Create Date: 2026-08-12 15:32:48.813864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f33fde83ba9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('file_path', sa.String(length=2048), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'TRANSCRIBING', 'EXTRACTING_CLIPS', 'COMPLETED', 'FAILED', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=2048), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=2048), nullable=True),
    sa.Column('virality_score', sa.Integer(), nullable=True),
    sa.Column('suggested_hooks', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_job_id'), 'clips', ['job_id'], unique=False)
    op.create_table('ab_experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clip_id', sa.String(length=36), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CONCLUDED', 'FAILED', name='abexperimentstatus', native_enum=False), nullable=False),
    sa.Column('variants', sa.JSON(), nullable=False),
    sa.Column('winning_variant_id', sa.String(length=36), nullable=True),
    sa.Column('learned_insight', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('concluded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clip_id'], ['clips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_experiments_clip_id'), 'ab_experiments', ['clip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ab_experiments_clip_id'), table_name='ab_experiments')
    op.drop_table('ab_experiments')
    op.drop_index(op.f('ix_clips_job_id'), table_name='clips')
    op.drop_table('clips')
    op.drop_table('jobs')
    # ### end Alembic commands ###
